### ISSUE TITLE
Составить интро

### ISSUE THREAD

**Issue by sofiia-chorna** [schernaya/homepage#4]
Составить интро (вступление), где в 2-4 предложениях описать, что заказчик делает, что нравится делать, что хочется делать лучше, что важно делать, и т.д.

**Comment by fiekium** [comment]
Hello! I am an American artist, film director, and producer, a leading figure in the visual art movement known as pop art. I blur the line between low and high by converting Coca-Cola bottles and ketchup packaging into high-value works of art. 

Привет! Я американский художник, кинорежиссер и продюсер, ведущая фигура в движении изобразительного искусства, известном как поп-арт. Я стираю границу между низменным и возвышенным, превращая бутылки Coca-Cola и упаковку кетчупа в ценные произведения искусства.

**Comment by sofiia-chorna** [comment]
Thanks!
