### ISSUE TITLE
Составить блок контактной информации

### ISSUE THREAD

**Issue by sofiia-chorna** [schernaya/homepage#5]
Ссылки на соцсети (Facebook или Instagram, и т.п.), номер телефона или адрес электронной почты, т.п. Может не все ссылки в мире, а только те, которые действительно уместны.

**Comment by fiekium** [comment]
Email: andywarhol@gmail.com
Instagram: thewarholmuseum
Facebook: Andy Warhol (https://www.facebook.com/AndyWarholArtist/)
Google Art: Andy Warhol (https://artsandculture.google.com/entity/andy-warhol/m0kc6)
The Factory, 231 East 47th Street, Manhattan, New York, USA
Фабрика, 231 Восточная 47-я улица, Манхэттен, Нью-Йорк, США

**Comment by sofiia-chorna** [comment]
Thanks!
