### ISSUE TITLE
Составить таймлайн

### ISSUE THREAD

**Issue by sofiia-chorna** [schernaya/homepage#6]
Составить список всех (важных) жизненных событий, памятных дат, достижений, периодов, которые дали приятный и неприятный опыт, и т.п. В этом конкретном случае длинных списков не бывает, бывают плохо свернутые, поэтому пакуем сюда всё подряд, а про "лишние" события можно будет промолчать позже. Список должен быть систематизирован и отсортирован таким образом, чтоб читатель быстро понял "паттерн" и мог легко ориентироваться в пространстве и времени этого резюме.

**Comment by fiekium** [comment]
RECENT
1979
Founded the New York Academy of Art.
1973
Directed the film Love with fashion designer Karl Lagerfeld in the title role.
1973
Published such books as The Philosophy of Andy Warhol and Exposures. Experimented extensively with video art, producing more than 60 films
1963
Opened his own art studio “The Factory”. The Factory quickly became one of New York City's premier cultural hotspots, a scene of lavish parties attended by the city's wealthiest socialites and celebrities
BACK THEN
1962 
Exhibited the now-iconic paintings of Campbell's soup cans.
1960
Created a design for cans of Coca-Cola. Started to explore silkscreening.
1950
Designer of shop windows, advertising posters, postcards in collaboration with Vogue and Harper's Bazaar.
1949
Graduated from Carnegie Institute for Technology with an Bachelor of Fine Arts degree

RECENT
1979 г.
Основал Нью-Йоркскую художественную академию.
1973
Режиссер фильма «Любовь» с модельером Карлом Лагерфельдом в главной роли.
1973
Опубликовал такие книги, как «Философия Энди Уорхола» и «Разоблачения». Экспериментировал с видео артом, снял более 60 фильмов.
1963 г.
Открыл собственную художественную студию «Фабрика». Фабрика быстро стала одним из главных культурных центров Нью-Йорка, местом проведения роскошных вечеринок, на которые собираются самые богатые светские люди и знаменитости города.
BACK THEN
1962 г.
Выставка ставших культовыми картин с изображением банок с супом Кэмпбелла.
1960 г.
Создал дизайн банок Кока-Колы. Начал изучать шелкографию.
1950
Дизайнер витрин, рекламных плакатов, открыток в сотрудничестве с Vogue и Harper's Bazaar.
1949 г.
Окончил Технологический институт Карнеги со степенью бакалавра изящных искусств.

**Comment by sofiia-chorna** [comment]
Got it. Thank you.
