### ISSUE TITLE
Составить дополнительные информационные блоки

### ISSUE THREAD

**Issue by sofiia-chorna** [schernaya/homepage#7]
Можно сделать резюме менее формальным, добавив дополнительные блоки, которые содержат полезную информацию, но подают её в "развлекательной" форме. Например, что нравится и не нравится, сильные и слабые стороны, перечень навыков или хобби, инфографика или же интерактивные модули, и т.п. Стоит написать контент такого блока раньше, чем начинать верстку, потому что его размеры будут влиять на размещение элементов на странице.

**Comment by fiekium** [comment]
LANGUAGES
ENGLISH, RUSSIAN

SKILLS
painting
silkscreening
photography
filmmaking

LIKES
Campbell's Soup 
alternative rock
gathering people
silver paint

DISLIKES
Homophobes

**Comment by fiekium** [comment]
ЯЗЫКИ
АНГЛИЙСКИЙ, РУССКИЙ

НАВЫКИ 
рисование
шелкография
фотография
кинопроизводство

НРАВИТСЯ
Суп Кэмпбелла
альтернативный рок
встречаться с новыми людей
серебряная краска

НЕ НРАВИТСЯ
Гомофобы

**Comment by sofiia-chorna** [comment]
Good, thanks
