### ISSUE TITLE
Добавить визуальную информацию

### ISSUE THREAD

**Issue by sofiia-chorna** [schernaya/homepage#8]
Добавить заглавное фото, известные картины.

**Comment by fiekium** [comment]
Main photo
https://m.spletnik.ru/img/2011/08/dasha/calendars/20110805-any-post.jpg

1. Campbell's Soup Cans
https://muzei-mira.com/templates/museum/images/paint/kempbell-yorxol+.jpg
2. Marilyn Diptych
https://artstartml.com/wp-content/uploads/2020/10/%D0%AD%D0%A36.jpg
3. Velvet underground & nico
https://upload.wikimedia.org/wikipedia/ru/0/0c/Velvet_Underground_and_Nico.jpg
4. Eight Elvises
https://muzei-mira.com/templates/museum/images/paint/8-elvisov-endi-yorxol+.jpg

**Comment by sofiia-chorna** [comment]
Thank you!
